# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-05 04:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OpenGraphObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200, verbose_name=b'URL')),
                ('pub_date', models.DateTimeField(verbose_name=b'Publication date')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name=b'Title')),
                ('site_name', models.CharField(blank=True, max_length=200, verbose_name=b'Site name')),
                ('author', models.CharField(blank=True, max_length=200, verbose_name=b'Author')),
                ('description', models.CharField(blank=True, max_length=1000, verbose_name=b'Description')),
                ('image', models.CharField(blank=True, max_length=1000, verbose_name=b'Image URL')),
                ('outlet', models.CharField(blank=True, max_length=200, verbose_name=b'Outlet')),
                ('ind_owned', models.BooleanField(default=False, verbose_name=b'Indigenous-owned')),
                ('shares_twitter', models.IntegerField(default=0, verbose_name=b'Twitter shares')),
                ('shares_facebook', models.IntegerField(default=0, verbose_name=b'Facebook shares')),
            ],
        ),
        migrations.CreateModel(
            name='Outlet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outlet', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TweetTopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name=b'Topic name')),
                ('count', models.IntegerField(default=0, verbose_name=b'Number of tweets')),
                ('enabled', models.BooleanField(default=True, verbose_name=b'Enabled')),
                ('sentiment_positive', models.FloatField(default=0.0, verbose_name=b'Percentage of tweets with positive sentiment')),
                ('sentiment_neutral', models.FloatField(default=0.0, verbose_name=b'Percentage of tweets with neutral sentiment')),
                ('sentiment_negative', models.FloatField(default=0.0, verbose_name=b'Percentage of tweets with negative sentiment')),
            ],
        ),
    ]
