# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-05 04:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_tweet'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='topic_10',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AddField(
            model_name='tweet',
            name='topic_11',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AddField(
            model_name='tweet',
            name='topic_12',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AddField(
            model_name='tweet',
            name='topic_13',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AddField(
            model_name='tweet',
            name='topic_14',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AddField(
            model_name='tweet',
            name='topic_15',
            field=models.CharField(blank=True, max_length=140),
        ),
    ]
