# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-05 05:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20161105_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='user_img',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
