# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-05 08:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_tweet_user_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='opengraphobject',
            name='manual',
            field=models.BooleanField(default=False, verbose_name=b'Manually updated'),
        ),
    ]
