# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-06 03:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_opengraphobject_manual'),
    ]

    operations = [
        migrations.AddField(
            model_name='outlet',
            name='json',
            field=models.CharField(blank=True, max_length=20000, verbose_name=b'Serialized JSON'),
        ),
        migrations.AlterField(
            model_name='opengraphobject',
            name='description',
            field=models.CharField(blank=True, max_length=2000, verbose_name=b'Description'),
        ),
    ]
