# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-06 04:25
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_auto_20161106_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='outlet',
            name='place',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
