# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-06 04:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_auto_20161106_1555'),
    ]

    operations = [
        migrations.RenameField(
            model_name='outlet',
            old_name='place',
            new_name='geometry',
        ),
        migrations.RenameField(
            model_name='outlet',
            old_name='outlet',
            new_name='name',
        ),
        migrations.AddField(
            model_name='outlet',
            name='_id',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
