# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-06 05:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_auto_20161106_1557'),
    ]

    operations = [
        migrations.RenameField(
            model_name='outlet',
            old_name='_id',
            new_name='outlet',
        ),
    ]
