# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-06 06:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_auto_20161106_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='outlet',
            name='facebook_url',
            field=models.CharField(blank=True, max_length=200, verbose_name=b'Facebook URL'),
        ),
        migrations.AddField(
            model_name='outlet',
            name='geojson',
            field=models.CharField(blank=True, max_length=10000, verbose_name=b'GeoJSON (serialized JSON)'),
        ),
        migrations.AddField(
            model_name='outlet',
            name='twitter_id_str',
            field=models.CharField(blank=True, max_length=200, verbose_name=b'Twitter ID'),
        ),
        migrations.AddField(
            model_name='outlet',
            name='website',
            field=models.CharField(blank=True, max_length=200, verbose_name=b'Website URL'),
        ),
        migrations.AddField(
            model_name='outlet',
            name='website_rss',
            field=models.CharField(blank=True, max_length=200, verbose_name=b'Website RSS'),
        ),
        migrations.AlterField(
            model_name='outlet',
            name='json',
            field=models.CharField(blank=True, max_length=20000, verbose_name=b'Full outlet (serialized JSON)'),
        ),
        migrations.AlterField(
            model_name='outlet',
            name='name',
            field=models.CharField(blank=True, max_length=200, verbose_name=b'Name'),
        ),
        migrations.AlterField(
            model_name='outlet',
            name='outlet',
            field=models.CharField(blank=True, max_length=200, verbose_name=b'Outlet ID'),
        ),
    ]
