# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-07 00:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0013_waypoint'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Waypoint',
        ),
    ]
