# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-07 03:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0014_delete_waypoint'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outlet',
            name='geojson',
        ),
    ]
