# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-07 06:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0016_outlet_names_other'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outlet',
            name='json',
        ),
        migrations.AddField(
            model_name='outlet',
            name='class_subtype',
            field=models.CharField(blank=True, max_length=200, verbose_name=b'Classification subcategory'),
        ),
        migrations.AddField(
            model_name='outlet',
            name='class_type',
            field=models.CharField(blank=True, max_length=200, verbose_name=b'Classification type'),
        ),
        migrations.AddField(
            model_name='outlet',
            name='description',
            field=models.CharField(blank=True, max_length=2000, verbose_name=b'Description'),
        ),
        migrations.AddField(
            model_name='outlet',
            name='email',
            field=models.CharField(blank=True, max_length=200, verbose_name=b'Email'),
        ),
        migrations.AddField(
            model_name='outlet',
            name='ind_owned',
            field=models.BooleanField(default=False, verbose_name=b'Indigenous owned'),
        ),
        migrations.AddField(
            model_name='outlet',
            name='phone_mobile',
            field=models.CharField(blank=True, max_length=200, verbose_name=b'Phone (mobile)'),
        ),
        migrations.AddField(
            model_name='outlet',
            name='phone_work',
            field=models.CharField(blank=True, max_length=200, verbose_name=b'Phone (work)'),
        ),
        migrations.AlterField(
            model_name='outlet',
            name='name',
            field=models.CharField(blank=True, max_length=200, verbose_name=b''),
        ),
    ]
