# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-15 08:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0017_auto_20161107_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opengraphobject',
            name='author',
            field=models.CharField(blank=True, max_length=200, verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='opengraphobject',
            name='description',
            field=models.CharField(blank=True, max_length=2000, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='opengraphobject',
            name='image',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Image URL'),
        ),
        migrations.AlterField(
            model_name='opengraphobject',
            name='ind_owned',
            field=models.BooleanField(default=False, verbose_name='Indigenous-owned'),
        ),
        migrations.AlterField(
            model_name='opengraphobject',
            name='manual',
            field=models.BooleanField(default=False, verbose_name='Manually updated'),
        ),
        migrations.AlterField(
            model_name='opengraphobject',
            name='outlet',
            field=models.CharField(blank=True, max_length=200, verbose_name='Outlet'),
        ),
        migrations.AlterField(
            model_name='opengraphobject',
            name='pub_date',
            field=models.DateTimeField(verbose_name='Publication date'),
        ),
        migrations.AlterField(
            model_name='opengraphobject',
            name='shares_facebook',
            field=models.IntegerField(default=0, verbose_name='Facebook shares'),
        ),
        migrations.AlterField(
            model_name='opengraphobject',
            name='shares_twitter',
            field=models.IntegerField(default=0, verbose_name='Twitter shares'),
        ),
        migrations.AlterField(
            model_name='opengraphobject',
            name='site_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Site name'),
        ),
        migrations.AlterField(
            model_name='opengraphobject',
            name='title',
            field=models.CharField(blank=True, max_length=200, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='opengraphobject',
            name='url',
            field=models.CharField(max_length=200, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='outlet',
            name='class_subtype',
            field=models.CharField(blank=True, max_length=200, verbose_name='Classification subcategory'),
        ),
        migrations.AlterField(
            model_name='outlet',
            name='class_type',
            field=models.CharField(blank=True, max_length=200, verbose_name='Classification type'),
        ),
        migrations.AlterField(
            model_name='outlet',
            name='description',
            field=models.CharField(blank=True, max_length=2000, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='outlet',
            name='email',
            field=models.CharField(blank=True, max_length=200, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='outlet',
            name='facebook_url',
            field=models.CharField(blank=True, max_length=200, verbose_name='Facebook URL'),
        ),
        migrations.AlterField(
            model_name='outlet',
            name='ind_owned',
            field=models.BooleanField(default=False, verbose_name='Indigenous owned'),
        ),
        migrations.AlterField(
            model_name='outlet',
            name='name',
            field=models.CharField(blank=True, max_length=200, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='outlet',
            name='names_other',
            field=models.CharField(blank=True, max_length=500, verbose_name='Other names (comma-separated)'),
        ),
        migrations.AlterField(
            model_name='outlet',
            name='outlet',
            field=models.CharField(blank=True, max_length=200, verbose_name='Outlet ID'),
        ),
        migrations.AlterField(
            model_name='outlet',
            name='phone_mobile',
            field=models.CharField(blank=True, max_length=200, verbose_name='Phone (mobile)'),
        ),
        migrations.AlterField(
            model_name='outlet',
            name='phone_work',
            field=models.CharField(blank=True, max_length=200, verbose_name='Phone (work)'),
        ),
        migrations.AlterField(
            model_name='outlet',
            name='twitter_id_str',
            field=models.CharField(blank=True, max_length=200, verbose_name='Twitter ID'),
        ),
        migrations.AlterField(
            model_name='outlet',
            name='website',
            field=models.CharField(blank=True, max_length=200, verbose_name='Website URL'),
        ),
        migrations.AlterField(
            model_name='outlet',
            name='website_rss',
            field=models.CharField(blank=True, max_length=200, verbose_name='Website RSS'),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='outlet',
            field=models.CharField(blank=True, max_length=200, verbose_name='Outlet'),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Publication date'),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='screen_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='@screen_name'),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='text',
            field=models.TextField(blank=True, verbose_name='Tweet text'),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='url',
            field=models.CharField(blank=True, max_length=200, verbose_name='Link to tweet'),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='url_user',
            field=models.CharField(blank=True, max_length=200, verbose_name='Link to user'),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='user_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='User name'),
        ),
        migrations.AlterField(
            model_name='tweettopic',
            name='count',
            field=models.IntegerField(default=0, verbose_name='Number of tweets'),
        ),
        migrations.AlterField(
            model_name='tweettopic',
            name='enabled',
            field=models.BooleanField(default=True, verbose_name='Enabled'),
        ),
        migrations.AlterField(
            model_name='tweettopic',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Topic name'),
        ),
        migrations.AlterField(
            model_name='tweettopic',
            name='sentiment_negative',
            field=models.FloatField(default=0.0, verbose_name='Percentage of tweets with negative sentiment'),
        ),
        migrations.AlterField(
            model_name='tweettopic',
            name='sentiment_neutral',
            field=models.FloatField(default=0.0, verbose_name='Percentage of tweets with neutral sentiment'),
        ),
        migrations.AlterField(
            model_name='tweettopic',
            name='sentiment_positive',
            field=models.FloatField(default=0.0, verbose_name='Percentage of tweets with positive sentiment'),
        ),
    ]
